name: QC Preflight Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  preflight:
    name: Run QC Preflight Checks
    uses: ynancher/qcom-reusable-workflows/.github/workflows/reusable-qcom-preflight-checks-orchestrator.yml@commit-msg-check
    with:
      enable-semgrep-scan: true
      enable-dependency-review: true
      enable-repolinter-check: true
      enable-copyright-license-check: true
      enable-commit-email-check: true
      enable-commit-msg-check: true
      enable-armor-checkers: false
      commit-msg-check-extra-options: '{"strict-line-length-check": false}'
    permissions:
      contents: read
      security-events: write
